### ISSUE TITLE
Some class/method are not available with Scala.js

### ISSUE THREAD

**Issue by exoego** [Comcast/ip4s#155]
This is a bug report .

* ip4s 1.4.0
* Scala 2.13.3
* Scala.js 1.1.1
* OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
* Ubuntu 20.04 LTS

When `Cidr.fromString(str)` is used, Scala.js failed to `fastOptJS`/`fullOptJS` due to:

```
[error] Referring to non-existent class com.comcast.ip4s.Cidr$
...
[error] Referring to non-existent method com.comcast.ip4s.Cidr$.fromString(java.lang.String)scala.Option
...
```

Same error happens when the apply method `Cidr(ip"10.123.45.67", 8)` is used.

### Note
I cloned this repository and run `testKitJS/test`, which includes test for `Cidr.fromString`.
The tests finished successfully on my end.
So I wonder this might be publishing issue ... ?

**Comment by matthughes** [comment]
@exoego Any chance you can create a minimal reproduction?  I'm running 1.4.0 as well and was able to use Cidr.fromString in my client side without a problem.  Is it every method in ip4s?

**Comment by exoego** [comment]
Hmm, I tried to create a minimum repro, but it run without a problem.
Maybe due to combination with other dependency...
I will reopen when I found a repro.
