### ISSUE TITLE
Enum for version of IP

### ISSUE THREAD

**Issue by Lasering** [Comcast/ip4s#172]
Suggestion - implement something like:

```scala
enum IpVersion {
  case V4, V6
}

class IpAddress {
  def version: IpVersion
}

class Ipv4Address {
  override def version: IpVersion = IpVersion.V4
}

class Ipv6Address {
  override def version: IpVersion = IpVersion.V6
}
```

Use cases:

1) Allows having configurations/settings per IP version:

```scala
val configs: Map[IpVersion, Long] = ???
val subnetId = configs.get(IpVersion.V4)
```

2) On a list of IpAddresses/Cidrs easily group them by version:

```scala
val cidrs: List[Cidr[IpAddress]] = ???
val perVersion: Map[IpVersion, List[Cidr[IpAddress]]] = cidrs.groupBy(_.address.version)
```

**Comment by mpilquist** [comment]
Sounds good to me.

**Comment by Lasering** [comment]
I can make a PR, what should I use to implement the enum? A Scala2 enum, a sealed trait ADT, enumeratum?

**Comment by mpilquist** [comment]
Let's do a sealed trait with objects in the companion -- so like your ADT above but put the V4/V6 objects in companion of `IpVersion`.
