### ISSUE TITLE
mdoc dependency

### ISSUE THREAD

**Issue by Lasering** [Comcast/ip4s#182]
mdoc is being included as a dependency in the [final pom](https://search.maven.org/artifact/com.comcast/ip4s-core_2.13/1.4-633db90/bundle). Not sure if it is intentional, but its inclusion makes a fat jar almost 3 times bigger.

**Comment by mpilquist** [comment]
No, definitely not intentional, thanks for spotting.

**Comment by mpilquist** [comment]
Fixed by bc08bb0099fd46fa6bde8ed490ef6b7997c48a84
