### ISSUE TITLE
Suggestion: CIDR could have a method that returns the number of IPs

### ISSUE THREAD

**Issue by Lasering** [Comcast/ip4s#187]
For example:
```scala
val cidr = ip"192.168.1.0" / 24
cidr.totalIps // returns 256
```

I didn't fully confirm if this is the correct implementation:
```scala
def totalIps: BigInt = {
  import scala.math._
  val maxPrefixBits: Double = address.fold(v4 => 32.0, v6 => 128.0)
  val ips = pow(2d, maxPrefixBits - prefixBits)
  BigDecimal(ips).setScale(0, BigDecimal.RoundingMode.HALF_UP).toBigInt
}
```

I can make a PR if it helps.

**Comment by mpilquist** [comment]
Sounds good to me. The implementation is much simpler if we use bit shifting. Something like: `1 << (address.fold(_ => 32, _ => 128) - prefixBits)`

**Comment by Lasering** [comment]
Its simpler for IPv4:
```scala
scala> 1L << (32 - 24) 
res1: Long = 256L
```
For IPv6 it does not work:
```scala
scala> 1L << (128 - 64) 
res2: Long = 1L
```

We could somehow return an Int for IPv4 and compute the value with bit shifting, and return a BigInt for IPv6.

**Comment by mpilquist** [comment]
Ha, right! That's what I get for multitasking. :)
