### ISSUE TITLE
Add toSsm/toAsm on MulticastJoin

### ISSUE THREAD

**Issue by matthughes** [Comcast/ip4s#2]
I propose to add the following to `MulticastJoin`

```scala
def toAsm: Option[AnySourceMulticastJoin[A]]
def toSsm: Option[SourceSpecificMulticastJoin[A]]
```

to make it easier working with these types.  I am constantly narrowing from MJ to SSM in my code and while fold makes it easy, it's very verbose.

**Comment by mpilquist** [comment]
Fixed in #3
