### ISSUE TITLE
Support for IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by applewil** [Comcast/ip4s#274]
#### Actual Behavior

`ip"::ffff:f:f"` returns an IPv6 address and throws an exception when invoking `toInetAddress`

```scala
ip"::ffff:f:f".toInetAddress // Exception in thread "main" java.lang.ClassCastException
```

#### Expected Behavior

I expect `ip"::ffff:f:f"` to return an IPv4 address like `InetAddress.getByName` does

```scala
ip"::ffff:f:f".toInetAddress // /0.15.0.15
```

**Comment by mpilquist** [comment]
Thanks for the bug report. I'm not sure how we can fix this one... `InetAddress.fromBytes` will always return an `Inet4Address` for an IPv4 mapped IPv6 address. I don't think there's any way to construct an `Inet6Address` for a IPv4 mapped address. If this is true, then we really need to change `toInetAddress` to always return `InetAddress` -- but that's a binary incompatible change.
