### ISSUE TITLE
Scala 3.0 should be used to publish Scala 3 artifacts

### ISSUE THREAD

**Issue by limansky** [Comcast/ip4s#341]
Scala 3.1.0 is not forward binary compatible with Scala 3.0. According to this recommendation https://scala-lang.org/blog/2021/10/21/scala-3.1.0-released.html#compatibility-notice libraries should be published with latest Scala 3.0 version (at least if any Scala 3.1 features aren't used).

**Comment by mpilquist** [comment]
Is the usage of 3.1 causing any issues for you? I've been releasing all libraries against 3.1 (e.g. scodec and fs2 as well, amongst others). I disagree with the advice offered in the 3.1.0 release notes, as I think it places too high a burden on library authors.

**Comment by limansky** [comment]
Well, I was trying to create PR to `pureconfig-ip4s`, and faced with this issue, since they use Scala 3.0 for publishing.

**Comment by limansky** [comment]
Meanwhile I don't really understand what kind of burden do you mean. Maintaining Scala libraries was always kind of pain, since it requires cross-building for different Scala 2 versions, but for Scala 3 it just require not to update the compiler, isn't it? So it supposed to make things simpler than it was before.

**Comment by mpilquist** [comment]
Right, which currently means libraries would be stuck on the EOL 3.0.2 release, without support for linting/warning suppression added in 3.1. 3.1.0 and 3.1.1-RC1 both have important fixes which some libraries require. I encourage folks to eagerly upgrade to 3.1.0 just like we do for Scala.js compiler releases, while we await a more sustainable solution from the Scala 3 team. 

Some discussion here: https://github.com/typelevel/cats/pull/4016
Some more on Discord here: https://discord.com/channels/632277896739946517/839257183782436945/900717227202981938

Re: the official recommendation:
>  In the meantime, we recommend testing your library with Scala 3.1.0 and 3.0.2, but publishing it with 3.0.2. This will allow downstream users to use your library even if they can’t update to Scala 3.1.0.

That's too much build trickery than I have the patience for. It's simple for simple builds but quickly gets very complicated and that complication all becomes irrelevant (hopefully) when Scala 3.2.0 is out, which should fix this situation.
