### ISSUE TITLE
Need more lenient SourceSpecificMulticastJoin

### ISSUE THREAD

**Issue by matthughes** [Comcast/ip4s#402]
SourceSpecificMulticastJoin correctly enforces that group IP is in the range 232/8 as defined by RFC 4607 ( https://datatracker.ietf.org/doc/html/rfc4607).  However, in practice, values outside this range are often used.  MulticastJoin is a sealed class so it cannot be extended outside of this library.

I propose we add a UnvalidatedSourceSpecificMulticastJoin or provide some way to bypass the range validation SourceSpecificMulticastJoin.

**Comment by mpilquist** [comment]
LenientSourceSpecificMulticastJoin makes sense to me, providing a source of type A and group of type Multicast.
