### ISSUE TITLE
Ciris Codecs

### ISSUE THREAD

**Issue by barryoneill** [Comcast/ip4s#452]
It'd be great if there were ciris codecs available as part of this project (unless I'm missing something that makes ciris work automatically with these classes).

I'd consider contributing a ip4s-ciris module - would there be interest in adopting it to this project?

**Comment by mpilquist** [comment]
Ciris codecs would be great! I think they'd have to live in the ciris repository, alongside the other modules here: https://github.com/vlovgr/ciris/tree/master/modules. Otherwise we'd have a build cycle (ip4s > ciris > http4s > ip4s).

**Comment by barryoneill** [comment]
Doh, I should have realised that. Makes perfect sense, thank you @mpilquist !

**Comment by vlovgr** [comment]
@barryoneill there are already some decoders for ip4s types in [ciris-http4s](https://github.com/vlovgr/ciris/blob/master/modules/http4s/shared/src/main/scala/ciris/http4s/http4s.scala), but feel free to contribute more if necessary.

**Comment by barryoneill** [comment]
Oh wow - host and port was exactly what I needed!  Thank you!
