### ISSUE TITLE
IpAddress should implement scala.Ordered

### ISSUE THREAD

**Issue by ryanstull** [Comcast/ip4s#59]
In the JVM ecosystem, the interface `java.lang.Comparable` is implemented by types that have a canonical ordering;  whereas `java.util.Comparator` is used for those that could have many sortings.  

In the scala ecosystem `scala.Ordered` and `scala.Ordering` implement, and take the place of these interfaces.

IpAddresses have a canonical ordering and thus they should implement `scala.Ordered`, which will also allow them to implement `java.lang.Comparable`, so they can inter-op with Java and Scala code based on these interfaces.

**Comment by mpilquist** [comment]
I think that's how we had it originally but then changed to an `Ordering` instance instead. Happy to review a PR that switches to `Ordered` instead as long as things generally work as well as now. :)

**Comment by mpilquist** [comment]
Fixed by #121
